### ISSUE TITLE
[Bug Report] Language Preference Core Setting sets Total Nat field to maximum amount

### ISSUE THREAD

**Issue by SantoII-github** [Lumenita/abfalter#11]
**Description**
When the Language Preference Core setting is set to anything other than "English" character Actor sheets have the "Total Nat" field of skills related to STR, DEX, WP or POW set to the maximum bonus of 100.

**Reproduction Steps**

1. Open an Anima Beyond Fantasy Alter world.
2. Click the Game Settings
3. Change the Language Preference setting to anything other than English
4. Check the Secondary Abilities of a Character Sheet and note the numbers have changed

**Screenshots**
Spanish: https://imgur.com/Qu6BbHg
English: https://imgur.com/9CnumJz

**Setup:**

- Foundry Version: 12.330 Stable
- System Version: Anima Beyond Fantasy Altered 1.4.2
- Browser: Tested both on Chrome and Firefox

**Comment by Lumenita** [comment]
Thats odd, I was able to replicate it, will have it fixed by the next update.
Thank you.

**Comment by Lumenita** [comment]
This should be fixed, if it is please close this ticket. If not, let me know :)

**Comment by SantoII-github** [comment]
Unfortunately still happening on a new world when using non-english languages.

Versions are:

- Foundry Version: 12.331 Stable
- System Version: Anima Beyond Fantasy Altered 1.4.3
- No modules

If there's any other info I may be able to provide in order to help, please let me know.

**Comment by Lumenita** [comment]
Sorry for the delay, I was in vacation, Lets solve this
Im having a hard time replicating it on my end this time.
I'm starting worlds in other languages and it works fine :/
If your foundry default language (before picking a system)  is not english, could you change it to english and try it out?

**Comment by SantoII-github** [comment]
Hope you enjoyed your vacation!

Foundry default language was already set to english: https://imgur.com/gU5z4EQ

I tested it again regardless just in case and took a screenshot of the relevant in-game setting and the character sheet side-by-side: https://imgur.com/RdcK15N

Would you like me to upload a world where I've reproduced this?

**Comment by Lumenita** [comment]
Wait, no need, I finally got it to max out
I'll fix it!
